// // Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// module CTLCore(
//   input         clock,
//                 reset,
//   output        io_sAxi_aw_ready,
//   input         io_sAxi_aw_valid,
//   input  [18:0] io_sAxi_aw_bits_addr,
//   input  [2:0]  io_sAxi_aw_bits_prot,
//   input  [5:0]  io_sAxi_aw_bits_id,
//   input  [2:0]  io_sAxi_aw_bits_size,
//   input  [7:0]  io_sAxi_aw_bits_len,
//   input  [1:0]  io_sAxi_aw_bits_burst,
//   input  [3:0]  io_sAxi_aw_bits_cache,
//   input         io_sAxi_aw_bits_lock,
//   output        io_sAxi_w_ready,
//   input         io_sAxi_w_valid,
//   input  [63:0] io_sAxi_w_bits_data,
//   input  [7:0]  io_sAxi_w_bits_strb,
//   input         io_sAxi_w_bits_last,
//                 io_sAxi_b_ready,
//   output        io_sAxi_b_valid,
//   output [1:0]  io_sAxi_b_bits_resp,
//   output [5:0]  io_sAxi_b_bits_id,
//   output        io_sAxi_ar_ready,
//   input         io_sAxi_ar_valid,
//   input  [18:0] io_sAxi_ar_bits_addr,
//   input  [2:0]  io_sAxi_ar_bits_prot,
//   input  [5:0]  io_sAxi_ar_bits_id,
//   input  [2:0]  io_sAxi_ar_bits_size,
//   input  [7:0]  io_sAxi_ar_bits_len,
//   input  [1:0]  io_sAxi_ar_bits_burst,
//   input  [3:0]  io_sAxi_ar_bits_cache,
//   input         io_sAxi_ar_bits_lock,
//                 io_sAxi_r_ready,
//   output        io_sAxi_r_valid,
//   output [63:0] io_sAxi_r_bits_data,
//   output [1:0]  io_sAxi_r_bits_resp,
//   output [5:0]  io_sAxi_r_bits_id,
//   output        io_sAxi_r_bits_last,
//                 io_complete
// );

//   assign io_sAxi_aw_ready = 1'h0;
//   assign io_sAxi_w_ready = 1'h0;
//   assign io_sAxi_b_valid = 1'h0;
//   assign io_sAxi_b_bits_resp = 2'h0;
//   assign io_sAxi_b_bits_id = 6'h0;
//   assign io_sAxi_ar_ready = 1'h0;
//   assign io_sAxi_r_valid = 1'h0;
//   assign io_sAxi_r_bits_data = 64'h0;
//   assign io_sAxi_r_bits_resp = 2'h0;
//   assign io_sAxi_r_bits_id = 6'h0;
//   assign io_sAxi_r_bits_last = 1'h0;
//   assign io_complete = 1'h0;
// endmodule

module IrisTopTmp (
    input  tri logic        clock,
    input  tri logic        reset,
    input  tri logic        txClock,

    // AXI Read Address Channel
    input  tri logic        axiData_ar_ready,
    output tri logic        axiData_ar_valid,
    output tri logic [31:0] axiData_ar_bits_addr,
    output tri logic [4:0]  axiData_ar_bits_id,
    output tri logic [2:0]  axiData_ar_bits_size,
    output tri logic [7:0]  axiData_ar_bits_len,
    output tri logic [1:0]  axiData_ar_bits_burst,
    output tri logic [3:0]  axiData_ar_bits_cache,
    output tri logic        axiData_ar_bits_lock,
    output tri logic [2:0]  axiData_ar_bits_prot,

    // AXI Read Data Channel
    output tri logic        axiData_r_ready,
    input  tri logic        axiData_r_valid,
    input  tri logic [63:0] axiData_r_bits_data,
    input  tri logic        axiData_r_bits_last,
    input  tri logic [4:0]  axiData_r_bits_id,
    input  tri logic [1:0]  axiData_r_bits_resp,

    // AXI Write Address Channel
    input  tri logic        axiData_aw_ready,
    output tri logic        axiData_aw_valid,
    output tri logic [31:0] axiData_aw_bits_addr,
    output tri logic [4:0]  axiData_aw_bits_id,
    output tri logic [2:0]  axiData_aw_bits_size,
    output tri logic [7:0]  axiData_aw_bits_len,
    output tri logic [1:0]  axiData_aw_bits_burst,
    output tri logic [3:0]  axiData_aw_bits_cache,
    output tri logic        axiData_aw_bits_lock,
    output tri logic [2:0]  axiData_aw_bits_prot,

    // AXI Write Data Channel
    input  tri logic        axiData_w_ready,
    output tri logic        axiData_w_valid,
    output tri logic [63:0] axiData_w_bits_data,
    output tri logic        axiData_w_bits_last,
    output tri logic [7:0]  axiData_w_bits_strb,

    // AXI Write Response Channel
    output tri logic        axiData_b_ready,
    input  tri logic        axiData_b_valid,
    input  tri logic [4:0]  axiData_b_bits_id,
    input  tri logic [1:0]  axiData_b_bits_resp,

    // JayLink TX Interface
    output tri logic        jaylink_tx_clock,
    output tri logic        jaylink_tx_flit_valid,
    output tri logic [7:0]  jaylink_tx_flit_bits,
    output tri logic        jaylink_tx_creditARW_free,
    output tri logic        jaylink_tx_replayPkgID,

    // JayLink RX Interface
    input  tri logic        jaylink_rx_clock,
    input  tri logic        jaylink_rx_flit_valid,
    input  tri logic [15:0] jaylink_rx_flit_bits,
    input  tri logic        jaylink_rx_creditRB_free,
    input  tri logic        jaylink_rx_replayPkgID
);

    // --- 内部临时连线：所有输出清零 ---

    // AXI AR Outputs
    assign axiData_ar_valid       = 1'b0;
    assign axiData_ar_bits_addr   = 32'h0;
    assign axiData_ar_bits_id     = 5'h0;
    assign axiData_ar_bits_size   = 3'h0;
    assign axiData_ar_bits_len    = 8'h0;
    assign axiData_ar_bits_burst  = 2'h0;
    assign axiData_ar_bits_cache  = 4'h0;
    assign axiData_ar_bits_lock   = 1'b0;
    assign axiData_ar_bits_prot   = 3'h0;

    // AXI R Outputs
    assign axiData_r_ready        = 1'b0;

    // AXI AW Outputs
    assign axiData_aw_valid       = 1'b0;
    assign axiData_aw_bits_addr   = 32'h0;
    assign axiData_aw_bits_id     = 5'h0;
    assign axiData_aw_bits_size   = 3'h0;
    assign axiData_aw_bits_len    = 8'h0;
    assign axiData_aw_bits_burst  = 2'h0;
    assign axiData_aw_bits_cache  = 4'h0;
    assign axiData_aw_bits_lock   = 1'b0;
    assign axiData_aw_bits_prot   = 3'h0;

    // AXI W Outputs
    assign axiData_w_valid        = 1'b0;
    assign axiData_w_bits_data    = 64'h0;
    assign axiData_w_bits_last     = 1'b0;
    assign axiData_w_bits_strb    = 8'h0;

    // AXI B Outputs
    assign axiData_b_ready        = 1'b0;

    // JayLink TX Outputs
    assign jaylink_tx_clock           = 1'b0;
    assign jaylink_tx_flit_valid      = 1'b0;
    assign jaylink_tx_flit_bits       = 8'h0;
    assign jaylink_tx_creditARW_free  = 1'b0;
    assign jaylink_tx_replayPkgID     = 1'b0;

    // 注：输入端口 (clock, reset, rx_flit 等) 在 Bbox 内部无需驱动。

endmodule